In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
df=pd.read_excel('/Users/mishakush/Desktop/Capstone_Project_DSMP1/data/raw/flats.xlsx')

In [4]:
df.head()

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,2 BHK Flat in Krishna Colony,https://www.99acres.com/2-bhk-bedroom-apartmen...,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ...",C68850746
1,2 BHK Flat in Ashok Vihar,https://www.99acres.com/2-bhk-bedroom-apartmen...,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ...",H68850564
2,2 BHK Flat in Sohna,https://www.99acres.com/2-bhk-bedroom-apartmen...,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ...",J68850120
3,2 BHK Flat in Sector 61 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,2023-12-01 00:00:00,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN,S68849476
4,2 BHK Flat in Sector 92 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ...",L47956793

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3028 entries, 0 to 3027
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3028 non-null   object
 1   link             3028 non-null   object
 2   society          3027 non-null   object
 3   price            3008 non-null   object
 4   area             3015 non-null   object
 5   areaWithType     3009 non-null   object
 6   bedRoom          3009 non-null   object
 7   bathroom         3009 non-null   object
 8   balcony          3009 non-null   object
 9   additionalRoom   1695 non-null   object
 10  address          3003 non-null   object
 11  floorNum         3007 non-null   object
 12  facing           2128 non-null   object
 13  agePossession    3008 non-null   object
 14  nearbyLocations  2914 non-null   object
 15  description      3009 non-null   object
 16  furnishDetails   2204 non-null   object
 17  features         2595 non-null   object
 18  rating           2677 non-null   object
 19  property_id      3009 non-null   object
dtypes: object(20)
memory usage: 473.3+ KB

In [6]:
df.duplicated().sum()

0

In [7]:
df.isnull().sum()

property_name         0
link                  0
society               1
price                20
area                 13
areaWithType         19
bedRoom              19
bathroom             19
balcony              19
additionalRoom     1333
address              25
floorNum             21
facing              900
agePossession        20
nearbyLocations     114
description          19
furnishDetails      824
features            433
rating              351
property_id          19
dtype: int64

In [8]:
df['society'].value_counts()

society
SS The Leaf3.8 ★                             73
Tulip Violet4.3 ★                            40
Shapoorji Pallonji Joyville Gurugram4.0 ★    39
Signature Global Park4.0 ★                   36
Shree Vardhman Victoria3.8 ★                 35
                                             ..
shree kirpalu gi sector 52                    1
Meditech Apartment                            1
Mariners Home                                 1
IMT View Society                              1
Spire Woods Now Ananda by Alpha corp          1
Name: count, Length: 639, dtype: int64

In [9]:
df.rename(columns={'area': 'price_per_sqft'},inplace=True)

In [10]:
df.drop(columns=['property_id','link'],inplace=True)

In [11]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,2023-12-01 00:00:00,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [12]:
df['society'].value_counts().shape

(639,)

In [14]:
import re
df['society'] = df['society'].apply(lambda name: re.sub(r'\d+(\.\d+)?\s?★', '', str(name)).strip()).str.lower()

In [15]:
df['society'].value_counts().shape

(605,)

In [26]:
df=df[df['price']!='Price on Request']

In [27]:
df = df[df['price'] != 'price']

In [28]:
def treat_price(x):
    if type(x)==float:
        return x
    else:
        if(x[1]=='Lac'):
            return round(float(x[0])/100,2)
        else:
            return round(float(x[0]),2)

In [31]:
df['price']=df['price'].str.split(' ').apply(treat_price)

In [32]:
df.sample(5)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1657,3 BHK Flat in Sector 49 Gurgaon,orchid petals,2.35,"₹ 11,559/sq.ft.",Super Built up area 2033(188.87 sq.m.)Built Up...,3 Bedrooms,3 Bathrooms,3 Balconies,Others,"Opposite Sapphire Mall Sohna Road Gurgaon, Sec...",15th of 15 Floors,West,1 to 5 Year Old,"['Sapphire Mall', 'Omaxe City Centre', 'BigBaz...",Check out this 3 bhk apartment for sale in orc...,"['2 Fan', '2 Light', '1 Chimney', '2 Wardrobe'...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction5 out of..."
1997,3 BHK Flat in Sector 86 Gurgaon,dlf the skycourt,1.60,"₹ 8,294/sq.ft.",Super Built up area 1929(179.21 sq.m.),3 Bedrooms,3 Bathrooms,1 Balcony,Pooja Room,"141, Sector 86 Gurgaon, Gurgaon, Haryana",14th of 19 Floors,North-East,1 to 5 Year Old,"['Sapphire 83 Mall', 'NH-8, Imt Manesar', 'Rao...",Only genuine buyer contact .Dealer excuse,NaN,"['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Construction5 out of..."
1666,3 BHK Flat in Sector 104 Gurgaon,ats triumph,1.85,"₹ 8,078/sq.ft.",Super Built up area 2290(212.75 sq.m.),3 Bedrooms,4 Bathrooms,3+ Balconies,"Servant Room,Study Room,Pooja Room,Store Room","1245, Sector 104 Gurgaon, Gurgaon, Haryana",14th of 27 Floors,East,1 to 5 Year Old,"['IFFCO Chowk Metro Station', 'The Esplanade M...",Ats triumph is one of gurgaon's most sought af...,"['7 Fan', '7 Light', '1 Modular Kitchen', 'No ...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4 out of 5', 'Construction5 out of..."
1294,3 BHK Flat in Sector 83 Gurgaon,emaar palm gardens,1.76,"₹ 9,263/sq.ft.",Super Built up area 1900(176.52 sq.m.)Built Up...,3 Bedrooms,3 Bathrooms,3 Balconies,Servant Room,"704, Sector 83 Gurgaon, Gurgaon, Haryana",6th of 16 Floors,North-West,1 to 5 Year Old,"[""V'Lante Mall"", 'NH 48 Gurugram', 'iGrow Mont...",This 3 bhk flat is located in emaar palm garde...,"['3 Wardrobe', '6 Fan', '3 Geyser', '10 Light'...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4 out of..."
2058,2 BHK Flat in Sector 71 Gurgaon,chd avenue,0.95,"₹ 7,917/sq.ft.",Built Up area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,No Balcony,NaN,"Sector 71, Sector 71 Gurgaon, Gurgaon, Haryana",5th of 5 Floors,South,undefined,"['Huda City Centre', 'Apna Mart', 'Rajiv Chowk...",Best in class property available at sector 71 ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Green Area5 out of 5', 'Construction3 out of..."

In [44]:
df['price_per_sqft']=df['price_per_sqft'].str.strip(' ').str.split('/').str.get(0).str.split(' ').str.get(1).str.strip().str.replace(',','').str.strip().astype(float)

In [45]:
df['areaWithType'].value_counts()

areaWithType
Super Built up area 1578(146.6 sq.m.)                                                                                     17
Super Built up area 1350(125.42 sq.m.)                                                                                    17
Super Built up area 1950(181.16 sq.m.)Carpet area: 1161 sq.ft. (107.86 sq.m.)                                             17
Super Built up area 1650(153.29 sq.m.)Carpet area: 1022.58 sq.ft. (95 sq.m.)                                              15
Super Built up area 2010(186.74 sq.m.)                                                                                    14
                                                                                                                          ..
Super Built up area 1620(150.5 sq.m.)Carpet area: 862.18 sq.ft. (80.1 sq.m.)                                               1
Super Built up area 1827.5(169.78 sq.m.)                                                                                   1
Super Built up area 2690(249.91 sq.m.)Built Up area: 2600 sq.ft. (241.55 sq.m.)Carpet area: 2240 sq.ft. (208.1 sq.m.)      1
Super Built up area 2217(205.97 sq.m.)Built Up area: 2098 sq.ft. (194.91 sq.m.)Carpet area: 1859 sq.ft. (172.71 sq.m.)     1
Super Built up area 3123(290.14 sq.m.)                                                                                     1
Name: count, Length: 1925, dtype: int64

In [46]:
df['bedRoom'].value_counts()

bedRoom
3 Bedrooms    1437
2 Bedrooms     944
4 Bedrooms     478
1 Bedroom      104
5 Bedrooms      31
6 Bedrooms       3
Name: count, dtype: int64

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3016 entries, 0 to 3027
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3016 non-null   object
 1   society          3016 non-null   object
 2   price            2996 non-null   float64
 3   price_per_sqft   3014 non-null   float64
 4   areaWithType     2997 non-null   object
 5   bedRoom          2997 non-null   object
 6   bathroom         2997 non-null   object
 7   balcony          2997 non-null   object
 8   additionalRoom   1692 non-null   object
 9   address          2991 non-null   object
 10  floorNum         2995 non-null   object
 11  facing           2123 non-null   object
 12  agePossession    2996 non-null   object
 13  nearbyLocations  2906 non-null   object
 14  description      2997 non-null   object
 15  furnishDetails   2200 non-null   object
 16  features         2590 non-null   object
 17  rating           2668 non-null   object
dtypes: float64(2), object(16)
memory usage: 447.7+ KB

In [49]:
df=df[~df['bedRoom'].isnull()]

In [52]:
df.shape

(2997, 18)

In [56]:
df['bedRoom']

0       2 Bedrooms
1       2 Bedrooms
2       2 Bedrooms
3       2 Bedrooms
4       2 Bedrooms
           ...
3023    3 Bedrooms
3024    5 Bedrooms
3025    3 Bedrooms
3026    3 Bedrooms
3027    4 Bedrooms
Name: bedRoom, Length: 2997, dtype: object

In [61]:
df['bedRoom']=df['bedRoom'].str.split(' ').str.get(0).str.strip().astype(int)

In [62]:
df.sample()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
314,4 BHK Flat in Sector 113 Gurgaon,m3m capital,2.37,11500.0,Built Up area: 2060 (191.38 sq.m.)Carpet area:...,4,4 Bathrooms,3+ Balconies,Study Room,"Sector 113, Sector 113 Gurgaon , Gurgaon, Haryana",20th of 23 Floors,East,By 2025,"['Phase 2 Metro Station', 'Global Foyer Mall',...","0km from delhi, 10 minutes distance from igi a...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...","['Centrally Air Conditioned', 'Security / Fire...",NaN

In [64]:
df['bathroom']=df['bathroom'].str.split(' ').str.get(0).str.strip().astype(int)

In [66]:
df['balcony'].value_counts()

balcony
3 Balconies     974
3+ Balconies    862
2 Balconies     749
1 Balcony       315
No Balcony       97
Name: count, dtype: int64

In [74]:
df['balcony']=df['balcony'].str.split(' ').str.get(0).replace('No','0').str.strip()

In [75]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,2023-12-01 00:00:00,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [78]:
df['additionalRoom'].value_counts()

additionalRoom
False    1692
True     1305
Name: count, dtype: int64

In [79]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,True,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,True,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,True,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,False,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,2023-12-01 00:00:00,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,False,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [80]:
df['additionalRoom'] = pd.read_excel('/Users/mishakush/Desktop/Capstone_Project_DSMP1/data/raw/flats.xlsx')['additionalRoom']

In [85]:
df['additionalRoom'].isnull().sum()

1305

In [86]:
df['additionalRoom'].fillna('not available',inplace=True)

In [88]:
df['additionalRoom'].value_counts()

additionalRoom
not available                                    1305
Servant Room                                      629
Study Room                                        232
Others                                            179
Pooja Room                                        132
Study Room,Servant Room                            81
Store Room                                         76
Pooja Room,Servant Room                            60
Servant Room,Others                                52
Servant Room,Pooja Room                            30
Study Room,Others                                  27
Pooja Room,Study Room,Servant Room,Others          25
Pooja Room,Study Room,Servant Room                 24
Servant Room,Store Room                            19
Pooja Room,Study Room                              13
Pooja Room,Study Room,Servant Room,Store Room      12
Study Room,Pooja Room                               8
Servant Room,Study Room                             8
Study Room,Servant Room,Store Room                  7
Pooja Room,Store Room                               6
Pooja Room,Others                                   6
Others,Servant Room                                 6
Servant Room,Study Room,Pooja Room,Store Room       6
Pooja Room,Servant Room,Others                      6
Study Room,Servant Room,Others                      5
Pooja Room,Store Room,Study Room,Servant Room       4
Pooja Room,Study Room,Store Room                    4
Servant Room,Pooja Room,Study Room,Store Room       3
Study Room,Pooja Room,Store Room                    3
Store Room,Servant Room                             3
Servant Room,Study Room,Store Room                  2
Pooja Room,Study Room,Others                        2
Study Room,Pooja Room,Servant Room                  2
Servant Room,Others,Store Room,Pooja Room           2
Servant Room,Others,Pooja Room                      2
Study Room,Servant Room,Pooja Room,Store Room       2
Others,Study Room                                   1
Servant Room,Study Room,Others                      1
Servant Room,Pooja Room,Study Room                  1
Servant Room,Study Room,Pooja Room                  1
Store Room,Pooja Room,Servant Room                  1
Servant Room,Pooja Room,Store Room,Study Room       1
Study Room,Store Room                               1
Store Room,Study Room                               1
Servant Room,Pooja Room,Store Room                  1
Study Room,Servant Room,Store Room,Pooja Room       1
Study Room,Servant Room,Pooja Room                  1
Pooja Room,Servant Room,Study Room,Store Room       1
Pooja Room,Study Room,Store Room,Servant Room       1
Store Room,Pooja Room                               1
Name: count, dtype: int64

In [104]:
 df['floorNum'] = pd.read_excel('/Users/mishakush/Desktop/Capstone_Project_DSMP1/data/raw/flats.xlsx')['floorNum']

In [105]:
df['floorNum']=df['floorNum'].str.split(' ').str.get(0).str.replace('Ground','0').str.replace('Basement','-1').str.replace('Lower','0').str.extract(r'(-?\d+)')

In [106]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NA,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NA,2023-12-01 00:00:00,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NA,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [107]:
df['facing'].isnull().sum()

0

In [108]:
df['facing'].fillna('NA',inplace=True)

In [109]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NA,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NA,2023-12-01 00:00:00,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NA,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [110]:
df.insert(loc=4,column='area',value=round((df['price']*10000000)/df['price_per_sqft']))

In [111]:
df.insert(loc=1,column='property_type',value='flat')

In [112]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,flat,apna enclave,0.50,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,flat,tulsiani easy in homes,0.40,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NA,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,flat,smart world orchard,1.47,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NA,2023-12-01 00:00:00,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,flat,parkwood westend,0.70,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2,2,3,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NA,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [113]:
df.shape

(2997, 20)

In [114]:
df.to_csv('flats_cleaned.csv',index=False)

## CLAUDE CLEANING

In [ ]:
# continue from my cleaned df (on a copy) and bring back the raw file for the columns that need re-parsing
import ast
raw = pd.read_excel('/Users/mishakush/Desktop/Capstone_Project_DSMP1/data/raw/flats.xlsx').loc[df.index]
cdf = df.copy()
cdf.shape

In [ ]:
# 1. duplicate listings: same property_id scraped twice (df.duplicated() gives 0 only because the rating list order differs) -> keep the latest copy
cdf['property_id'] = raw['property_id']
print(cdf['property_id'].duplicated().sum())
cdf = cdf[~cdf['property_id'].duplicated(keep='last')]
# 2. one listing has no price at all -> useless as a target
cdf = cdf[cdf['price'].notnull()]
cdf.shape

In [ ]:
# 3. society: redo from raw so only the rating (d.d ★) is removed, not digits of the name (dlf new town heights 1 / 2, godrej 101 ...)
def clean_society(name):
    if pd.isnull(name):
        return 'independent'
    name = re.sub(r'\d\.\d\s?★', '', name)
    return re.sub(r'\s+', ' ', name).strip().lower().replace('appartment', 'apartment')

cdf['society'] = raw['society'].apply(clean_society)
# same society written with different spacing / hyphens -> most common spelling
key = cdf['society'].str.replace(r'[^a-z0-9]', '', regex=True)
cdf['society'] = cdf.groupby(key)['society'].transform(lambda s: s.mode()[0])
cdf['society'] = cdf['society'].replace({
    'ansals api esencia': 'ansal api esencia', 'ansal height 86': 'ansal heights 86',
    'breeze global heights': 'breez global heights', 'essel tower': 'essel towers',
    'sidhivinayak apartments': 'siddhi vinayak apartments',
    'ss': 'ss the leaf',   # sector 85 listings with the same flat sizes as ss the leaf
    '.': 'independent', 'nul': 'independent', 'not applicable': 'independent',
    'apartment': 'independent', 'builder floor': 'independent', 'rwa': 'independent'})
cdf['society'].nunique()

In [ ]:
# 4. sector / locality from property_name
def get_sector(name):
    loc = name.split(' in ', 1)[1].lower()
    m = re.search(r'sector[\s-]*(\d+)\s*([a-z])?\b', loc)
    if m is None:
        return re.sub(r'\s+', ' ', re.sub(r'(?<!new) gurgaon$', '', loc)).strip()
    sector = 'sector ' + m.group(1) + (m.group(2) or '')
    if 'sohna' in loc:
        sector += ' sohna'
    elif 'manesar' in loc:
        sector += ' imt manesar'
    return sector

cdf.insert(loc=3, column='sector', value=cdf['property_name'].apply(get_sector))
cdf['sector'].nunique()

In [ ]:
# 5. price: treat_price rounded Lac prices to 2 decimals (17.5 Lac -> 0.18, 24.5 Lac -> 0.24) -> keep the exact value in crore
def price_in_crore(x):
    value, unit = x.split(' ')
    return round(float(value) / 100, 4) if unit == 'Lac' else float(value)

cdf['price'] = raw['price'].loc[cdf.index].apply(price_in_crore)

In [ ]:
# 6. areaWithType -> 3 numeric columns in sq.ft., fixing the unit / typing mistakes on the way
def parse_areas(row):
    out = {'area_fixed': False}
    labels = {'super_built_up_area': 'Super Built up area', 'built_up_area': 'Built Up area', 'carpet_area': 'Carpet area'}
    for col, label in labels.items():
        m = re.search(label + r':? ?([\d.]+)(?: sq\.ft\.)? ?(?:\(([\d.]+) sq\.m\.\))?', row['areaWithType'])
        if m is None:
            out[col] = np.nan
            continue
        value = float(m.group(1))
        if m.group(2) is None:
            # no (sq.m.) conversion shown -> the number itself was entered in sq.m.
            area = value * 10.7639
            if row['price'] * 10000000 / area < 2000:      # ...unless that gives an impossible rate: it was sq.ft. all along
                area = value
                out['area_fixed'] = True
        else:
            sqm = float(m.group(2))
            # number not in sq.ft. (sq.yd.) -> convert from the sq.m. figure
            area = value if abs(value / sqm - 10.7639) < 0.1 else sqm * 10.7639
            while row['price'] * 10000000 / area < 2000:    # decimal point lost: 569243 is really 569.243
                area = area / 10
                out['area_fixed'] = True
        if area < 100 or row['price'] * 10000000 / area > 100000:   # a zero lost: 72 sq.ft. flat, 4 BHK of 700 sq.ft. for 14 crore
            area = area * 10
            out['area_fixed'] = True
        out[col] = round(area, 2)
    return pd.Series(out)

areas = cdf.apply(parse_areas, axis=1)
for i, col in enumerate(['super_built_up_area', 'built_up_area', 'carpet_area']):
    cdf.insert(loc=8 + i, column=col, value=areas[col].astype(float))
areas['area_fixed'].sum()

In [ ]:
# 7. area (my column = price / price_per_sqft) is only right when the site's rate is: the rate is stale where the price was changed
#    after posting, and wrong where the area was wrong -> if it matches none of the listed areas, take the listed area and redo the rate
implied = cdf['price'] * 10000000 / cdf['price_per_sqft']
listed = cdf[['super_built_up_area', 'built_up_area', 'carpet_area']]
matches = listed.sub(implied, axis=0).abs().div(implied, axis=0).lt(0.05).any(axis=1)
listed_area = cdf['super_built_up_area'].fillna(cdf['built_up_area']).fillna(cdf['carpet_area'])
cdf['area'] = round(implied.where(matches, listed_area))
cdf.loc[~matches, 'price_per_sqft'] = round(cdf['price'] * 10000000 / cdf['area'])
(~matches).sum()

In [ ]:
# 8. floors: floorNum as a number + total floors of the building (was thrown away)
cdf['floorNum'] = cdf['floorNum'].astype(float).astype('Int64')
total_floors = raw['floorNum'].str.extract(r'of (\d+) Floors')[0].astype(float).astype('Int64')
cdf.insert(loc=cdf.columns.get_loc('floorNum') + 1, column='total_floors', value=total_floors)

In [ ]:
# 9. facing: 'NA' is read back as NaN by pd.read_csv -> use 'unknown'
cdf['facing'] = cdf['facing'].replace('NA', 'unknown')
# 10. agePossession: dates (Excel turned 'Dec 2023' into datetimes), 'By 2024', 'Within 6 months' all mean not ready yet
def clean_age(x):
    if pd.isnull(x) or x == 'undefined':
        return 'unknown'
    if 'Year Old' in str(x):
        return x
    return 'Under Construction'

cdf['agePossession'] = cdf['agePossession'].apply(clean_age)
cdf['agePossession'].value_counts()

In [ ]:
# 11. additionalRoom: same rooms in a different order were different categories
cdf['additionalRoom'] = cdf['additionalRoom'].apply(lambda x: ', '.join(sorted(x.lower().split(','))))
cdf['additionalRoom'].nunique()

In [ ]:
# 12. address: remove flat / unit number at the start, extra spaces, and fill the missing ones from property_name
def clean_address(row):
    address = row['address']
    if pd.isnull(address):
        return row['property_name'].split(' in ', 1)[1] + ', Gurgaon, Haryana'
    parts = [re.sub(r'\s+', ' ', p).strip() for p in address.split(',')]
    while len(parts) > 3 and re.fullmatch(r'[\w/-]*\d[\w/-]*', parts[0]) and not parts[0].lower().startswith('sector'):
        parts = parts[1:]
    return ', '.join(p for p in parts if p)

cdf['address'] = cdf.apply(clean_address, axis=1)

In [ ]:
# 13. list columns: missing -> [], extra spaces / repeated items removed, rating sorted so the same rating always looks the same
def clean_list(x, sort=False):
    if pd.isnull(x):
        return '[]'
    items = [re.sub(r'\s+', ' ', i).strip() for i in ast.literal_eval(x)]
    items = list(dict.fromkeys(i for i in items if i))
    return str(sorted(items) if sort else items)

for col in ['nearbyLocations', 'furnishDetails', 'features']:
    cdf[col] = cdf[col].apply(clean_list)
cdf['rating'] = cdf['rating'].apply(clean_list, sort=True)

In [ ]:
# 14. nearbyLocations: same place written in different ways -> one name
places = cdf['nearbyLocations'].apply(ast.literal_eval)
alias = {'indira gandhi intl airport': 'Indira Gandhi International Airport', 'igi airport': 'Indira Gandhi International Airport',
         'dwarka expy': 'Dwarka Expressway'}
all_places = places.explode().dropna()
common = all_places.groupby(all_places.str.lower()).agg(lambda v: v.mode()[0]).to_dict()
cdf['nearbyLocations'] = places.apply(lambda l: str(list(dict.fromkeys(alias.get(p.lower(), common[p.lower()]) for p in l))))

In [ ]:
# 15. description: line breaks / repeated spaces -> single space (keeps one listing on one csv line)
cdf['description'] = cdf['description'].str.replace(r'\s+', ' ', regex=True).str.strip()

In [ ]:
cdf = cdf.drop(columns=['property_id']).reset_index(drop=True)
cdf.info()

In [ ]:
cdf.to_csv('/Users/mishakush/Desktop/Capstone_Project_DSMP1/data/processed/claude_cleaned_flats.csv', index=False)